<?php
include ("blocks/bd.php");/*Connecting to BD!*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD /xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru" xml:lang="ru">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Планшеты в Минске, купить планшет недорого ^Cooler.by</title>
    <meta name="keywords" content="Планшеты в Минске, купить планшет недорого"/>
    <meta name="description" content=""/>
    <link href="default.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="planshety/planshety.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="shortcut icon" href="favicon.ico"/>
    <script type="text/javascript" src="js/prototype.js"></script>
    <script type="text/javascript" src="js/scriptaculous.js?load=effects,builder"></script>
    <script type="text/javascript" src="js/lightbox.js"></script>
    <link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <link href="css/tablet.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="css/style.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="css/global.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="css/jquery.lightbox-0.5.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="css/jquery.treeview.css" media="screen" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="js/jquery.lightbox-0.5.js"></script>
    <script type="text/javascript" src="js/jquery.treeview.js"></script>
    <script type="text/javascript" src="js/jquery.cookie.js"></script>
    <script type="text/javascript" src="js/scripts.js"></script>
    <script type="text/javascript" src="js/jquery.jcarousel.js"></script>
    <script type="text/javascript" src="js/flyshit.js"></script>
</head>
<body>
<!-- начало стр -->
<div id="wrapper">

    <?php include ("index/header-callme.txt"); ?>

    <!-- start page -->
    <div id="page">
        <div id="bgtop"></div>
        <div id="bgbottom">
            <!-- start menu -->

            <?php include ("index/menu.txt"); ?>
            <?php
                if (isset($_GET['id']))
                {
                    $idTablet = htmlspecialchars(trim($_GET['id']));
                }
                $result = mysql_query("SELECT tablet.*,number_of_cores_tablet.*,design_tablet.*,manufacture_tablet.*,clock_speed_tablet.*,screen_size_tablet.*,ram_tablet.*,operating_system_tablet.*,
                                        battery_capacity_tablet.*,built_in_speakers_tablet.*,case_material_tablet.*,cpu_tablet.*,graphics_accelerator_tablet.*,internal_memory_tablet.*,
                                        length_tablet.*,number_of_active_pixels_front_camera_tablet.*,number_of_active_pixels_tablet.*,operating_system_version_tablet.*,
                                        screen_resolution_tablet.*,thickness_tablet.*,type_of_matrix_screen_tablet.*,weight_tablet.*,
                                        width_tablet.*, image_name_tablet.id_tablet as id_tablet_image,image_name_tablet.name_image_name
                                       FROM  tablet
                                       LEFT JOIN number_of_cores_tablet ON number_of_cores_tablet.id_number_of_cores = tablet.number_of_cores
                                       LEFT JOIN design_tablet ON design_tablet.id_design = tablet.design
                                       LEFT JOIN manufacture_tablet ON manufacture_tablet.id_manufacture = tablet.manufacture
                                       LEFT JOIN clock_speed_tablet ON clock_speed_tablet.id_clock_speed = tablet.clock_speed
                                       LEFT JOIN screen_size_tablet ON screen_size_tablet.id_screen_size = tablet.screen_size
                                       LEFT JOIN ram_tablet ON ram_tablet.id_ram = tablet.ram
                                       LEFT JOIN image_name_tablet ON image_name_tablet.id_image_name = tablet.image_name
                                       LEFT JOIN operating_system_tablet ON operating_system_tablet.id_operating_system = tablet.operating_system
                                       LEFT JOIN battery_capacity_tablet ON battery_capacity_tablet.id_battery_capacity = tablet.battery_capacity
                                       LEFT JOIN built_in_speakers_tablet ON built_in_speakers_tablet.id_built_in_speakers = tablet.built_in_speakers
                                       LEFT JOIN case_material_tablet ON case_material_tablet.id_case_material = tablet.case_material
                                       LEFT JOIN cpu_tablet ON cpu_tablet.id_cpu = tablet.cpu
                                       LEFT JOIN graphics_accelerator_tablet ON graphics_accelerator_tablet.id_graphics_accelerator = tablet.graphics_accelerator
                                       LEFT JOIN internal_memory_tablet ON internal_memory_tablet.id_internal_memory = tablet.internal_memory
                                       LEFT JOIN length_tablet ON length_tablet.id_length = tablet.length
                                       LEFT JOIN number_of_active_pixels_front_camera_tablet ON number_of_active_pixels_front_camera_tablet.id_number_of_active_pixels_front_camera = tablet.number_of_active_pixels_front_camera
                                       LEFT JOIN number_of_active_pixels_tablet ON number_of_active_pixels_tablet.id_number_of_active_pixels = tablet.number_of_active_pixels
                                       LEFT JOIN operating_system_version_tablet ON operating_system_version_tablet.id_operating_system_version = tablet.operating_system_version
                                       LEFT JOIN screen_resolution_tablet ON screen_resolution_tablet.id_screen_resolution = tablet.screen_resolution
                                       LEFT JOIN thickness_tablet ON thickness_tablet.id_thickness = tablet.thickness
                                       LEFT JOIN type_of_matrix_screen_tablet ON type_of_matrix_screen_tablet.id_type_of_matrix_screen = tablet.type_of_matrix_screen
                                       LEFT JOIN weight_tablet ON weight_tablet.id_weight = tablet.weight
                                       LEFT JOIN width_tablet ON width_tablet.id_width = tablet.width
                                       WHERE tablet.id_tablet =" . $idTablet , $db);

                if (!$result)
                {
                    echo "<p>Запрос на выборку не прошел!<br /><strong>Код ошибки:</strong></p>";
                    exit (mysql_error());
                }
                if (!(mysql_num_rows($result) > 0))
                {
                    echo "<p>Нет записей!</p>";
                    exit ();
                }

                $rowTablet = mysql_fetch_assoc($result);
                $i =0;
            ?>
            <!-- начало Right -->
            <div id="right"><?php include ("index/soc-seti.txt"); ?>
                <h1>Планшет</h1>

                <div id="text">
                    <h1><?php echo $rowTablet['name_tablet'];?></h1>
                    <div class='cena-sist-bl' style="margin: 26px 70px 0 0;">Планшет  <span class="cenagl"><?php echo $rowTablet['cost'] .  ' '; ?></span> у.е.   </div>
                    <div id='podbor' style="border:none;">

                        <form method='post'>
                            <table style="float:right;margin-top: 24px;margin-right: 100px;margin-bottom: -5px">
                                <tr>
                                    <td>
                                        <button id='show-ocb-form<?=$i;?>' class='kupi-sist-bl' >Купить</button>


                                        <div class='ocb-form' id='ocb-form-wrap<?=$i;?>' style='display: none'>
                                            <div class='ocb-form-header'>

                                                <div class='ocb-form-header-caption'>Быстрый заказ</div>
                                                <div class='ocb-form-header-close'></div>
                                            </div>
                                            <div id='ocb-form<?=$i;?>'>
                                                <div id='ocb-params<?=$i;?>'>
                                                    <input type='hidden' id='titleSystemBlock<?=$i;?>' value='<?=$myrow['name_tablet'];?>'/>
                                                    <input type='hidden' id='itemCost<?=$i;?>' value='<?=$myrow['cost'];?>'/>
                                                    <div class='ocb-form-field'>
                                                        <label>Ваше имя
                                                            <ins>*</ins>
                                                        </label>
                                                        <input type='text' name='new_order<?=$i;?>[FIO]' value='' id='ocb-id-FIO<?=$i;?>'/>

                                                        <div id='ocb-id-FIO<?=$i;?>-error<?=$i;?>' class='ocb-error-msg'>Обязательно укажите ваше имя
                                                        </div>

                                                    </div>
                                                    <div class='ocb-form-field'>
                                                        <label>Контактный телефон
                                                            <ins>*</ins>
                                                        </label>
                                                        <select name='operator<?=$i;?>'
                                                                style='width: 70px; text-align: left; margin-right: 10px' id='operator<?=$i;?>'>
                                                            <option value='velcom'>Velcom</option>
                                                            <option value='mts'>МТС</option>
                                                            <option value='life'>life</option>
                                                        </select><input type='text' name='new_order<?=$i;?>[PHONE]' value='' id='ocb-id-PHONE<?=$i;?>'
                                                                        style='width: 250px'/>

                                                        <div id='ocb-id-PHONE<?=$i;?>-error<?=$i;?>' class='ocb-error-msg'>Обязательно укажите
                                                            контактный телефон
                                                        </div>

                                                    </div>

                                                    <div class='intaro-modules-button ptichka'>
                                                        <input type='submit' value='Отправить заказ' id='ocb-form-button<?=$i;?>'
                                                               name='ocb_form_button<?=$i;?>'/>
                                                    </div>
                                                    <div class='ocb-form-loader'></div>
                                                </div>
                                            </div>
                                            <div class='ocb-form-result' id='ocb-form-result<?=$i;?>'>
                                                <div class='ocb-result-icon-success'>Спасибо за заказ!</div>
                                                <div class='ocb-result-icon-fail'>Ошибка!</div>

                                                <div class='ocb-result-text'>В ближайшее время наш менеджер свяжется с вами.</div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </form>
                    </div>
                    <br/><br/><br/><br/>
                    Планшеты стали в наши дни очень популярными. Это сочетание телефона и нетбука плотно вошло в жизнь современно человека из-за своей функциональности и компактности.
                    Выход в интернет, чтение книг, просмотр фильмов, функции GPS-навигатора и многое другое всегда под рукой. Если и Вы решили присоединиться к той части населения,
                    которая идёт в ногу со временем, то Вы  попали по адресу. На нашем сайте можно купить планшет в Минске недорого и с гарантией. Обратившись к нам, Вы сможете подобрать в Минске недорогой и очень производительный планшет.
                </div>
<!--            *-->
            <link rel="stylesheet" type="text/css" href="css/slider-style/style.css" />
            <link rel="stylesheet" type="text/css" href="css/slider-style/jquery.jscrollpane.css" media="all" />
                     <script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
<!--            <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>-->
            <script type="text/javascript" src="js/slider/jquery.easing.1.3.js"></script>
            <!-- the jScrollPane script -->
            <script type="text/javascript" src="js/slider/jquery.mousewheel.js"></script>
            <script type="text/javascript" src="js/slider/jquery.contentcarousel.js"></script>

            <div id="ca-container" class="ca-container">
                <div class="ca-wrapper">
                    <div class="ca-item ca-item-<?php echo $i;?>">
                        <span class="img-slide"><img  src='images/tablet_images/<?php echo $rowImageNameTabletSelect['name_image_name']?>_small.jpg' alt='Планшет' title='Планшет'/></span>
                    </div>
                    <?php
                    $resultImageNameTabletSelect = mysql_query("SELECT * FROM image_name_tablet WHERE image_name_tablet.id_tablet=".$idTablet, $db);
                    $i=1;
                    while ($rowImageNameTabletSelect = mysql_fetch_assoc($resultImageNameTabletSelect))
                    {?>
                        <div class="ca-item ca-item-<?php echo $i;?>">
                            <span class="img-slide"><img  src='images/tablet_images/<?php echo $rowImageNameTabletSelect['name_image_name']?>_small.jpg' alt='Планшет' title='Планшет'/></span>
                        </div>
                    <?php

                    }
                    ?>
<!--                    <div class="ca-item ca-item-1">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
<!--                    <div class="ca-item ca-item-2">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
<!--                    <div class="ca-item ca-item-3">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
<!--                    <div class="ca-item ca-item-4">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
<!--                    <div class="ca-item ca-item-5">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
<!--                    <div class="ca-item ca-item-6">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
<!--                    <div class="ca-item ca-item-7">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
<!--                    <div class="ca-item ca-item-8">-->
<!--                        <span class="img-slide"><img  src='images/tablet_images/panasonic_small.jpg' alt='Планшет' title='Планшет'/></span>-->
<!--                    </div>-->
                </div>
            </div>
            <script type="text/javascript">
                $('#ca-container').contentcarousel();
            </script>
<!--            *-->
            <!--                ********************************************************************************************************-->
            <style>

                .pdtable td {
                    padding: 7px 10px;
                }

                .pdtable td.pline {
                    padding: 0;
                }

                .pdtable tr {
                    font-size: 11px;
                }

                .pdtable tr.pdsection {
                    background-color: #EEEEEE;
                    color: #000000;
                    font: bold 14px Arial, Helvetica, sans-serif;
                }

                .pdtable tr.pdsection td {
                    border-bottom: 1px solid #CCCCCC;
                    border-top: 1px solid #CCCCCC;
                    vertical-align: top;
                }

                .phed tr td {
                    background-color: #4E91DC;
                    color: #FFFFFF;
                    font: 9px Tahoma, Verdana, Geneva, Arial, Helvetica, sans-serif;
                    height: 20px;
                    padding: 0px 9px;
                }

                .phed tr td a:link, .phed tr td a:visited {
                    color: #FFFFFF;
                    text-decoration: underline;
                }

                .pline2 td {
                    border-bottom: 1px solid #CCCCCC;
                }

                .pline3 td {
                    border-bottom: 1px solid #EEEEEE;
                }

                .pline {
                    background: url(/pic/grey1.gif) repeat-x;
                }

                .pline2 td {
                    border-bottom: 1px solid #CCCCCC;
                }

                .pline3 td {
                    border-bottom: 1px solid #EEEEEE;
                }

                .pltable th {
                    text-align: left;
                    font-weight: normal;
                    padding: 15px 10px 5px 10px;
                    /*border-bottom: 1px solid #CCCCCC;*/
                }

                .pltable td {
                    text-align: left;
                    vertical-align: top;
                    width: 33%;
                    padding: 5px 10px;
                }

                .pline2 td {
                    border-bottom: 1px solid #CCCCCC;
                }

                .pline3 td {
                    border-bottom: 1px solid #EEEEEE;
                }

                .pltable th {
                    text-align: left;
                    font-weight: normal;
                    padding: 15px 10px 5px 10px;
                    /*border-bottom: 1px solid #CCCCCC;*/
                }

                .pltable td {
                    text-align: left;
                    vertical-align: top;
                    width: 33%;
                    padding: 5px 10px;
                }

            </style>
            <!--                ********************************************************************************************************-->
            <br/>
            <table width="70%" cellspacing="0" cellpadding="0" border="0" class="pdtable">
            <tbody>
            <tr class="pdsection">
                <td colspan="2">Основные</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <div class="par-name">
                        <p class="">Конструкция</p>
                    </div>
                </td>
                <td>
                    <?php echo $rowTablet['name_design'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <div class="par-name">
                        <p class="">Диагональ экрана</p>
                    </div>
                </td>
                <td>
                    <?php echo $rowTablet['name_screen_size'];?>"&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Операционная система
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_operating_system'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Версия операционной системы
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_operating_system_version'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Процессор
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_cpu'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Графический ускоритель
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_graphics_accelerator'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Оперативная память
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_ram'];?> ГБ&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Внутренняя память
                    </p>

                </td>
                <td>
                    <?php echo $rowTablet['name_internal_memory'];?> ГБ&nbsp;
                </td>
            </tr>

            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Количество ядер
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_number_of_cores'];?>4&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Тактовая частота
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_clock_speed'];?>&nbsp;МГц&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Материал корпуса
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_case_material'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Емкость аккумулятора
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_battery_capacity'];?>&nbsp;
                </td>
            </tr>

            <tr class="pdsection">
                <td colspan="2">Габариты и вес</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Длина
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_length'];?>&nbsp;мм&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Ширина
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_width'];?>&nbsp;мм&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Толщина
                    </p>

                </td>
                <td>
                    <?php echo $rowTablet['name_thickness'];?>&nbsp;мм&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Вес
                    </p>

                </td>
                <td>
                    <?php echo $rowTablet['name_weight'];?>&nbsp;г&nbsp;
                </td>
            </tr>
            <tr class="pdsection">
                <td colspan="2">Датчики</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Акселерометр
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['accelerometer']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>

                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Гироскоп
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['gyroscope']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Датчик приближения
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['proximity_sensor']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>
                </td>
            </tr>

            <tr class="pdsection">
                <td colspan="2">Экран</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Разрешение экрана
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_screen_resolution'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Тип матрицы экрана
                    </p>
                </td>
                <td>
                    <?php echo $rowTablet['name_type_of_matrix_screen'];?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Мультитач
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['multi_touch']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>
                </td>
            </tr>

            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Защита от царапин
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['protection_from_scratches']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Датчик освещенности
                    </p>

                </td>
                <td>
                    <?php echo ($rowTablet['the_light_sensor']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>&nbsp;
                </td>
            </tr>
            <tr class="pdsection">
                <td colspan="2">Хранение данных</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            Карты памяти
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['memory_cards']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' . $rowTablet['text_memory_cards'] :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pdsection">
                <td colspan="2">Камера и звук</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Встроенная камера
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['built-in_camera']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Количество активных пикселей
                    </p>

                </td>
                <td>
                <?php echo ($rowTablet['name_number_of_active_pixels'])?>&nbsp;Мп&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Количество активных пикселей фронтальной камеры
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['number_of_active_pixels_front_camera'])?>&nbsp;Мп&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                        Встроенный микрофон
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['built-in_microphone']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            Встроенные динамики
                    </p>

                </td>
                <td>
                    <?php echo ($rowTablet['built_in_speakers'])?>&nbsp;
                </td>
            </tr>
            <tr class="pdsection">
                <td colspan="2">Интерфейсы и коммуникации</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            Bluetooth
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['bluetooth']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' . $rowTablet['text_bluetooth'] :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            LAN
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['lan']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            WiFi
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['wifi']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' . $rowTablet['text_wifi'] :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>&nbsp;
                </td>
            </tr>
                       <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            3G-модем
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['3g_modem']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' . $rowTablet['text_3g_modem'] :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            USB 2.0
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['usb_2']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            USB 3.0
</p>
                </td>
                <td>
                    <?php echo ($rowTablet['usb_3']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            HDMI
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['hdmi']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                         alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            DisplayPort
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['display_port']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                           alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                                             alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            Аудио выходы (3.5 мм jack)
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['audio_outputs']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                           alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                                             alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            Док-порт
                    </p>

                </td>
                <td>
                    <?php echo ($rowTablet['docking_port']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                           alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>  &nbsp;
                </td>
            </tr>
            <tr class="pdsection">
                <td colspan="2">Навигация</td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            GPS/A-GPS
                    </p>

                </td>
                <td>
                    <?php echo ($rowTablet['gps']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                           alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?>&nbsp;
                </td>
            </tr>
            <tr class="pline2">
                <td class="pdinfohead">
                    <p class="">
                            Электронный компас</a>
                    </p>
                </td>
                <td>
                    <?php echo ($rowTablet['electronic_compass']) ? '<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_yes.gif" title="Да"
                           alt="Да">' :'<img width="12" border="0" height="12" src="http://catalog.onliner.by/pic/ico_no.gif" title="Нет"
                         alt="Нет">'?> &nbsp;
                </td>
            </tr>
            <tr>
                <td class="pdinfohead">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <script>
//                &lt;
//                !--
//                var on_cap = 1;
//                function on_capt() {
//                    if (on_cap == 1) {
//                        document.getElementById("cap_img").src = "/kcaptcha/?rand=448";
//                        document.getElementById("cap_tr1").style.display = "none";
//                        document.getElementById("cap_tr").style.display = "";
//                    }
//                    on_cap = 0;
//                }
//                -- &gt;
            </script>

            </tbody>
            </table>
            <!--                ********************************************************************************************************-->


            <div id="text_footer">

            </div>
            </div>
            <div style="clear: both;">&nbsp;</div>
        </div>
    </div>
    <hr />
    <!-- start footer -->
    <?php include ("index/footer.txt"); ?>

</div>
<?php include ("index/metrika_jivo.txt"); ?>
<?php

for($j=0;$j<=$i;$j++)
{
    printf(" <script type='text/javascript'>
$(document).ready(function() {
$('#show-ocb-form{$j}').live('click', function() {
$('#ocb-form-wrap{$j}').show();
$('#ocb-form{$j}').show();
$('#ocb-form-result{$j}').hide();
return !1;
});

$('.ocb-form-header-close').live('click', function() {
$('.ocb-error-msg').each(function(index) { $(this).hide(); });
$('.ocb-result-icon-success').hide();
$('.ocb-result-icon-fail').hide();
$('#ocb-form-wrap{$j}').fadeOut();
return !1;
});

$('button.intaro-modules-button.disabled, .intaro-modules-button.disabled input').live('click', function() {
return false;
});

$('#ocb-form-button{$j}').live('click', function() {
$('.ocb-error-msg').each(function(index) { $(this).hide(); });
var fieldId, fieldVal, checked = !0, self = $(this);
$('input[name^=\"new_order{$j}\"]').each(function() {
fieldId = $(this).attr('id');
fieldVal = $(this).val();
if (fieldVal=='') {
$('#' + fieldId + '-error{$j}').show();
checked = !1;
}
});
if (!checked) return !1;
$('.intaro-modules-button', $(this)).addClass('disabled');
$('.ocb-form-loader').show();

if(!$('#ocb-antispam{$j}').length) {
$('#ocb-params{$j}').prepend(\"<input id='ocb-antispam' type='hidden' name='antispam' value=''>\");
}

$.ajax({
url: \"/send_mail.php\",
data: \"firstname=\" + $(\"#ocb-id-FIO{$j}\").val() + \"&mobile_phone=\" + $(\"#ocb-id-PHONE{$j}\").val() + \"&title=\" + $(\"#titleSystemBlock{$j}\").val() + \"&price=\" + $(\"#itemCost{$j}\").val() + \"&mobile_operator=\" + $(\"#operator{$j}\").val(),
type: 'POST',
dataType: 'json',
error: function(obj, text, err) {
},
success: function(data) {
if(data.ok!='Y') {
$('.ocb-result-icon-fail').show();
$('.ocb-result-text').text(data.msg);
} else {
$('.ocb-result-icon-success').show();
if ($('#cart_line{$j}').length > 0)
$('#cart_line{$j}').html(data.msg);
}
$('.ocb-form-loader').hide();
$('.intaro-modules-button', self).removeClass('disabled');
$('#ocb-form{$j}').hide();
$('#ocb-form-result{$j}').show();
window.setTimeout(function() { $('.ocb-form-header-close').click(); }, 3000);
}
});
return !1;
});
});

</script>
");
}

?>
</body>
</html>
