<?php
include ("blocks/bd.php");/*Connecting to BD!*/
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD /xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru" xml:lang="ru">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Планшеты в Минске, купить планшет недорого ^Cooler.by</title>
    <meta name="keywords" content="Планшеты в Минске, купить планшет недорого"/>
    <meta name="description" content=""/>
    <link href="default.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="planshety/planshety.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="shortcut icon" href="favicon.ico"/>
    <script type="text/javascript" src="js/prototype.js"></script>
    <script type="text/javascript" src="js/scriptaculous.js?load=effects,builder"></script>
    <script type="text/javascript" src="js/lightbox.js"></script>
    <link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>

    <link href="css/style.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="css/global.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="css/jquery.lightbox-0.5.css" media="screen" rel="stylesheet" type="text/css"/>
    <link href="css/jquery.treeview.css" media="screen" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="js/jquery.lightbox-0.5.js"></script>
    <script type="text/javascript" src="js/jquery.treeview.js"></script>
    <script type="text/javascript" src="js/jquery.cookie.js"></script>
    <script type="text/javascript" src="js/scripts.js"></script>
    <script type="text/javascript" src="js/jquery.jcarousel.js"></script>
    <script type="text/javascript" src="js/flyshit.js"></script>
</head>
<body>
<!-- начало стр -->
<div id="wrapper">

    <?php include ("index/header-callme.txt"); ?>

    <!-- start page -->
    <div id="page">
        <div id="bgtop"></div>
        <div id="bgbottom">
            <!-- start menu -->

            <?php include ("index/menu.txt"); ?>
            <?php
                if (isset($_GET['id']))
                {
                    $idTablet = htmlspecialchars(trim($_GET['id']));
                }
                $result = mysql_query("SELECT * FROM  tablet WHERE id_tablet =" . $idTablet , $db);

                if (!$result)
                {
                    echo "<p>Запрос на выборку не прошел!<br /><strong>Код ошибки:</strong></p>";
                    exit (mysql_error());
                }
                if (!(mysql_num_rows($result) > 0))
                {
                    echo "<p>Нет записей!</p>";
                    exit ();
                }

                $rowTablet = mysql_fetch_assoc($result);
                $i =0;
            ?>
            <!-- начало Right -->
            <div id="right"><?php include ("index/soc-seti.txt"); ?>
                <h1>Планшеты</h1>
                <div id='podbor'>
                    <h1><?php echo $rowTablet['name_tablet'];?></h1>
                    <form method='post'>
                        <table style="float:right;margin-top: 24px;margin-right: 100px;margin-bottom: -5px">
                            <tr>
                                <td>
                                    <button id='show-ocb-form<?=$i;?>' class='kupi-sist-bl' >Купить</button>


                                    <div class='ocb-form' id='ocb-form-wrap<?=$i;?>' style='display: none'>
                                        <div class='ocb-form-header'>

                                            <div class='ocb-form-header-caption'>Быстрый заказ</div>
                                            <div class='ocb-form-header-close'></div>
                                        </div>
                                        <div id='ocb-form<?=$i;?>'>
                                            <div id='ocb-params<?=$i;?>'>
                                                <input type='hidden' id='titleSystemBlock<?=$i;?>' value='<?=$myrow['name_tablet'];?>'/>
                                                <input type='hidden' id='itemCost<?=$i;?>' value='<?=$myrow['cost'];?>'/>
                                                <div class='ocb-form-field'>
                                                    <label>Ваше имя
                                                        <ins>*</ins>
                                                    </label>
                                                    <input type='text' name='new_order<?=$i;?>[FIO]' value='' id='ocb-id-FIO<?=$i;?>'/>

                                                    <div id='ocb-id-FIO<?=$i;?>-error<?=$i;?>' class='ocb-error-msg'>Обязательно укажите ваше имя
                                                    </div>

                                                </div>
                                                <div class='ocb-form-field'>
                                                    <label>Контактный телефон
                                                        <ins>*</ins>
                                                    </label>
                                                    <select name='operator<?=$i;?>'
                                                            style='width: 70px; text-align: left; margin-right: 10px' id='operator<?=$i;?>'>
                                                        <option value='velcom'>Velcom</option>
                                                        <option value='mts'>МТС</option>
                                                        <option value='life'>life</option>
                                                    </select><input type='text' name='new_order<?=$i;?>[PHONE]' value='' id='ocb-id-PHONE<?=$i;?>'
                                                                    style='width: 250px'/>

                                                    <div id='ocb-id-PHONE<?=$i;?>-error<?=$i;?>' class='ocb-error-msg'>Обязательно укажите
                                                        контактный телефон
                                                    </div>

                                                </div>

                                                <div class='intaro-modules-button ptichka'>
                                                    <input type='submit' value='Отправить заказ' id='ocb-form-button<?=$i;?>'
                                                           name='ocb_form_button<?=$i;?>'/>
                                                </div>
                                                <div class='ocb-form-loader'></div>
                                            </div>
                                        </div>
                                        <div class='ocb-form-result' id='ocb-form-result<?=$i;?>'>
                                            <div class='ocb-result-icon-success'>Спасибо за заказ!</div>
                                            <div class='ocb-result-icon-fail'>Ошибка!</div>

                                            <div class='ocb-result-text'>В ближайшее время наш менеджер свяжется с вами.</div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                <div id="text">
                    Планшеты стали в наши дни очень популярными. Это сочетание телефона и нетбука плотно вошло в жизнь современно человека из-за своей функциональности и компактности.
                    Выход в интернет, чтение книг, просмотр фильмов, функции GPS-навигатора и многое другое всегда под рукой. Если и Вы решили присоединиться к той части населения,
                    которая идёт в ногу со временем, то Вы  попали по адресу. На нашем сайте можно купить планшет в Минске недорого и с гарантией. Обратившись к нам, Вы сможете подобрать в Минске недорогой и очень производительный планшет.
                </div>



                <div id="text_footer">

                </div>
            </div>
            <div style="clear: both;">&nbsp;</div>
        </div>
    </div>
    <hr />
    <!-- start footer -->
    <?php include ("index/footer.txt"); ?>

</div>
<?php include ("index/metrika_jivo.txt"); ?>
<?php

for($j=0;$j<=$i;$j++)
{
    printf(" <script type='text/javascript'>
$(document).ready(function() {
$('#show-ocb-form{$j}').live('click', function() {
$('#ocb-form-wrap{$j}').show();
$('#ocb-form{$j}').show();
$('#ocb-form-result{$j}').hide();
return !1;
});

$('.ocb-form-header-close').live('click', function() {
$('.ocb-error-msg').each(function(index) { $(this).hide(); });
$('.ocb-result-icon-success').hide();
$('.ocb-result-icon-fail').hide();
$('#ocb-form-wrap{$j}').fadeOut();
return !1;
});

$('button.intaro-modules-button.disabled, .intaro-modules-button.disabled input').live('click', function() {
return false;
});

$('#ocb-form-button{$j}').live('click', function() {
$('.ocb-error-msg').each(function(index) { $(this).hide(); });
var fieldId, fieldVal, checked = !0, self = $(this);
$('input[name^=\"new_order{$j}\"]').each(function() {
fieldId = $(this).attr('id');
fieldVal = $(this).val();
if (fieldVal=='') {
$('#' + fieldId + '-error{$j}').show();
checked = !1;
}
});
if (!checked) return !1;
$('.intaro-modules-button', $(this)).addClass('disabled');
$('.ocb-form-loader').show();

if(!$('#ocb-antispam{$j}').length) {
$('#ocb-params{$j}').prepend(\"<input id='ocb-antispam' type='hidden' name='antispam' value=''>\");
}

$.ajax({
url: \"/send_mail.php\",
data: \"firstname=\" + $(\"#ocb-id-FIO{$j}\").val() + \"&mobile_phone=\" + $(\"#ocb-id-PHONE{$j}\").val() + \"&title=\" + $(\"#titleSystemBlock{$j}\").val() + \"&price=\" + $(\"#itemCost{$j}\").val() + \"&mobile_operator=\" + $(\"#operator{$j}\").val(),
type: 'POST',
dataType: 'json',
error: function(obj, text, err) {
},
success: function(data) {
if(data.ok!='Y') {
$('.ocb-result-icon-fail').show();
$('.ocb-result-text').text(data.msg);
} else {
$('.ocb-result-icon-success').show();
if ($('#cart_line{$j}').length > 0)
$('#cart_line{$j}').html(data.msg);
}
$('.ocb-form-loader').hide();
$('.intaro-modules-button', self).removeClass('disabled');
$('#ocb-form{$j}').hide();
$('#ocb-form-result{$j}').show();
window.setTimeout(function() { $('.ocb-form-header-close').click(); }, 3000);
}
});
return !1;
});
});

</script>
");
}

?>
</body>
</html>
