<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD /xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="ru" xml:lang="ru">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Планшеты в Минске, купить планшет недорого ^Cooler.by</title>
    <meta name="keywords" content="Планшеты в Минске, купить планшет недорого"/>
    <meta name="description" content=""/>
    <link href="default.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="planshety/planshety.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="shortcut icon" href="favicon.ico"/>
    <script type="text/javascript" src="js/prototype.js"></script>
    <script type="text/javascript" src="js/scriptaculous.js?load=effects,builder"></script>
    <script type="text/javascript" src="js/lightbox.js"></script>
    <link rel="stylesheet" href="css/lightbox.css" type="text/css" media="screen" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
</head>
<body>
<!-- начало стр -->
<div id="wrapper">

    <?php include ("index/header-callme.txt"); ?>

    <!-- start page -->
    <div id="page">
        <div id="bgtop"></div>
        <div id="bgbottom">
            <!-- start menu -->

            <?php include ("index/menu.txt"); ?>

            <!-- начало Right -->
            <div id="right"><?php include ("index/soc-seti.txt"); ?>
                <h1>Планшеты</h1>
                <div id="text">
                    Планшеты стали в наши дни очень популярными. Это сочетание телефона и нетбука плотно вошло в жизнь современно человека из-за своей функциональности и компактности.
                    Выход в интернет, чтение книг, просмотр фильмов, функции GPS-навигатора и многое другое всегда под рукой. Если и Вы решили присоединиться к той части населения,
                    которая идёт в ногу со временем, то Вы  попали по адресу. На нашем сайте можно купить планшет в Минске недорого и с гарантией. Обратившись к нам, Вы сможете подобрать в Минске недорогой и очень производительный планшет.
                </div>



                <div id="text_footer">

                </div>
            </div>
            <div style="clear: both;">&nbsp;</div>
        </div>
    </div>
    <hr />
    <!-- start footer -->
    <?php include ("index/footer.txt"); ?>

</div>
<?php include ("index/metrika_jivo.txt"); ?>
</body>
</html>
